#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 -Target Default

# Tests
test: off

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- Source\packages -> Source\**\packages.config
- Tools -> build.ps1

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  files:
    - README.md
